name: SSH to EC2 and Run Command

on:
  push:
    branches:
      - main

jobs:
  ssh_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub Actions Runner IP
        id: runner_ip
        run: |
          RUNNER_IP=$(hostname -I | awk '{print $1}')
          echo "Host IP Address: $RUNNER_IP"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Allow GitHub Actions Runner IP on EC2 security group
        run: |
          # Replace EC2_INSTANCE_IP with your EC2 instance's public IP or hostname
          # Replace SECURITY_GROUP_ID with your EC2 security group ID
          aws ec2 authorize-security-group-ingress --group-id sg-0a7d556a06013a58d --protocol tcp --port 22 $RUNNER_IP/32
      - name: SSH to EC2 and Run Command
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@EC2_INSTANCE_IP 'ls -a'
