name: SSH to EC2 and Run Command

on:
  push:
    branches:
      - main

jobs:
  ssh_to_ec2:
    runs-on: ubuntu-latest
    outputs:
      runner_ip: ${{ steps.get_ip.outputs.runner_ip }}
      runner_cidr: ${{ steps.get_ip.outputs.runner_cidr }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Runner IP and CIDR
        id: get_ip
        run: |
          ip_cidr=$(hostname -I)
          runner_ip=$(echo "$ip_cidr" | awk '{print $1}')
          runner_cidr=$(echo "$ip_cidr" | awk '{print $1"/32"}')
          echo "::set-output name=runner_ip::$runner_ip"
          echo "::set-output name=runner_cidr::$runner_cidr"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
          script: |
            echo "login successfull"
      
          
      - name: Allow GitHub Actions Runner IP on EC2 security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id sg-0a7d556a06013a58d --protocol tcp --port 22 --cidr 0.0.0.0/0

      - name: SSH to EC2 and Run Command
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@184.72.89.114 
      
