name: SSH to EC2 and Run Command

on:
  push:
    branches:
      - main

jobs:
  ssh_to_ec2:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Runner IP and CIDR
        id: get_ip
        run: |
          RUNNER_IP=$(curl -s ifconfig.me)
          CIDR=$(echo "$RUNNER_IP" | awk -F. '{printf "%s.%s.%s.0/24", $1, $2, $3}')
          echo "::set-output name=cidr::$CIDR"

      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Allow GitHub Actions Runner IP on EC2 security group
        run: |
          CIDR=$(echo "${{ steps.get_ip.outputs.cidr }}")
          aws ec2 authorize-security-group-ingress --group-id sg-0a7d556a06013a58d --protocol tcp --port 22 --cidr "$CIDR"

      - name: SSH into EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@184.72.89.114 'echo "hostname is $(hostname)"'

      - name: Revoke GitHub Actions Runner IP from EC2 security group
        if: ${{ always() }}
        run: |
          CIDR=$(echo "${{ steps.get_ip.outputs.cidr }}")
          aws ec2 revoke-security-group-ingress --group-id sg-0a7d556a06013a58d --protocol tcp --port 22 --cidr "$CIDR"
          
      - name: SSH into EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@184.72.89.114 'echo "hostname is $(hostname)"'
        
