name: SSH to EC2 and Run Command

on:
  push:
    branches:
      - main

jobs:
  ssh_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get GitHub Actions Runner IP
        id: runner_ip
        run: |
          RUNNER_IP=$(hostname -I | awk '{print $1}')
          echo "Host IP Address: $RUNNER_IP"
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      
